### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by jwrichards1982** [MykhailoOpryshok/Borukva-Food#11]
I am making a 1.21.1 "modpack" for personal use and tried adding in this mod. Upon launch in modrinth, it just stops after  clicking play. Just in case my setup has way too many mods and things registering, until I have time to review and maybe remove things, I have modrinth assigning 16384GB to the instance. I am not sure what else needs to be known, but I'll attach the crash log and answer questions later. I have some free time fomr work so I'll be as repsonsivbe as possible.
[crash-2024-09-02_17.17.17-client.txt](https://github.com/user-attachments/files/16842010/crash-2024-09-02_17.17.17-client.txt)

**Comment by jwrichards1982** [comment]
I'll also add in the latest.log in case that provides more info.
[latest.log](https://github.com/user-attachments/files/16842018/latest.log)

**Comment by MykhailoOpryshok** [comment]
download this https://modrinth.com/mod/polymer/version/0.9.11+1.21.1

**Comment by jwrichards1982** [comment]
That did it! Thanks a bunch!
