### ISSUE TITLE
Item Groups are badly named.

### ISSUE THREAD

**Issue by Patbox** [MykhailoOpryshok/Borukva-Food#3]
General convention for item groups is that they contain mod name. For example `PolyFactory: Colored Variants` or `Building Blocks (Blokus)`. This mod's item groups use generic names `Items` and `Blocks and tools`.  Ideally both of these groups could be merged into single BorukvaFood item group, or at least get prefixed/suffixed with mod name. Additionally it should use the same casing/name style as vanilla (`Tools & Utilities`)

**Comment by MykhailoOpryshok** [comment]
![зображення](https://github.com/user-attachments/assets/30acab68-3c57-45ee-8363-ebccc466e088)
![зображення](https://github.com/user-attachments/assets/e114a60c-c16a-4ec6-bd24-b1ad195dd08d)
fixed
