### ISSUE TITLE
Add other language locale

### ISSUE THREAD

**Issue by noiverre** [MykhailoOpryshok/Borukva-Food#7]
Currently there are some parts which are in RU, would prefer other language if possible
![image](https://github.com/user-attachments/assets/0803d6a8-0ec7-48e0-8067-64ca69a40c7e)
![image](https://github.com/user-attachments/assets/b9bbd2b3-28cf-486d-893c-093b0983d235)

**Comment by MykhailoOpryshok** [comment]
![зображення](https://github.com/user-attachments/assets/09b17c71-9e49-4023-ad03-c12e66b83272)

**Comment by MykhailoOpryshok** [comment]
This is a Ukrainian language, not russian
![зображення](https://github.com/user-attachments/assets/c463ef58-91d2-4444-809e-2f9e926e0e89)
![зображення](https://github.com/user-attachments/assets/7e73671d-84aa-40d5-91fd-94b5a285c27d)
![зображення](https://github.com/user-attachments/assets/140d628d-38d8-42bc-8bcd-924f2fd3ab26)
fixed !

**Comment by noiverre** [comment]
Thanks for the correction, I'm not familliar with languages that uses cyrillic script
