### ISSUE TITLE
Borukva Food 0.1.2 not working on 1.21.1

### ISSUE THREAD

**Issue by jwrichards1982** [MykhailoOpryshok/Borukva-Food#8]
Borukva Food 0.1.2 is listed as working on 1.21.1, but this cannot happen; 
It relies on BorukvaUtils 0.1.1 at least which is only listed as working on 1.21. This cannot be verified as working as it in turn relies on Filament, the latest only working on 1.21. Latest version of Filament  (0.5.2) refuses to register on 1.21.1, wanting 1.21 at the most.
Borukva Food should be delisted  as being 1.21.1 compatible until Filament updates, or is no longer needed as a requirement for BorukvaUtils

**Comment by Stikulzon** [comment]
damn

**Comment by Stikulzon** [comment]
BorukvaUtils updated.

**Comment by jwrichards1982** [comment]
Apologies for not responding sooner. I got real busy.  Things are working now! I have a week off work now, so I can play with this more. Thank you! I appreciate your time and effort!
